#Configuações do Microservice
spring:
  application:
    name: msc-booksws
      
#Porta deste Microservice
server:
  port: 9002

#Configuracoes relacionadas ao registro no eureka
eureka:
  client:
    enabled: true
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://servicediscovery:8761/eureka/
  instance:
    prefer-ip-address: true

#Configuracoes relacionadas ao Actuator
info:
  app:
    name:@project.name@
    description:@project.description@
    version:@project.version@  